### ISSUE TITLE
Re-implement online search

### ISSUE THREAD

**Issue by McBaumwolle** [krlvm/BeautySearch#1]
If you install BeautySearch, it automatically **disables** web search. 
![image](https://user-images.githubusercontent.com/67203883/90955253-4ac93780-e47c-11ea-8718-a1ddd63da6f3.png)
I think it was intentionally added, but it shouldn't, many people including me use it.

**Comment by Loldogs** [comment]
Any updates on this?

> Thanks for the idea, I figured out how to re-implement the web search, even how to add a custom search provider instead of Bing (Google, etc.)

**Comment by krlvm** [comment]
> Any updates on this?
> 
> > Thanks for the idea, I figured out how to re-implement the web search, even how to add a custom search provider instead of Bing (Google, etc.)

I managed to display search results in the Search Window, but I still need to do some research to figure out how to force open the links in an external browser.

**Comment by TillKnollmann** [comment]
> > Any updates on this?
> > > Thanks for the idea, I figured out how to re-implement the web search, even how to add a custom search provider instead of Bing (Google, etc.)
> 
> I managed to display search results in the Search Window, but I still need to do some research to figure out how to force open the links in an external browser.

I am thrilled for this! Currently, only the missing online search is keeping me from installing your software. Keep up the good work!

**Comment by KibSquib48** [comment]
> > Any updates on this?
> > > Thanks for the idea, I figured out how to re-implement the web search, even how to add a custom search provider instead of Bing (Google, etc.)
> 
> I managed to display search results in the Search Window, but I still need to do some research to figure out how to force open the links in an external browser.

very excited to hear this! I like having search results in the start search but I hate how bing has no dark mode so for the time being I'm using duckduckgo and would absolutely love to see it integrated into the system search menu

**Comment by Loldogs** [comment]
Are there any new updates on this or is this feature not possible?

> Thanks for the idea, I figured out how to re-implement the web search, even how to add a custom search provider instead of Bing (Google, etc.)

**Comment by krlvm** [comment]
I've published a [beta version](https://github.com/krlvm/BeautySearch/releases/tag/v1.3-preview) with some limitations.

**Comment by Loldogs** [comment]
> I've published a [beta version](https://github.com/krlvm/BeautySearch/releases/tag/v1.3-preview) with some limitations.

I have tried it out. The embedded window does not fit the search section  and the "search the web" button (which seems to disappear when no local results are found) has to be clicked on for online results. Hope there is a fix

**Comment by krlvm** [comment]
> The embedded window does not fit the search section
Can you provide a screenshot, please?

**Comment by Loldogs** [comment]
> > The embedded window does not fit the search section
> 
> Can you provide a screenshot, please?

![image](https://user-images.githubusercontent.com/28437673/111909089-4cd89080-8a75-11eb-8e20-650d899600bf.png)

**Comment by senolfndk** [comment]
not loading
![SharedScreenshot](https://user-images.githubusercontent.com/52818836/128634689-01d3ef18-4d53-42c0-ad83-cfca0c42355f.jpg)

**Comment by krlvm** [comment]
@senolfndk Try to restart the Installer and Install it again, if it still not work, you can manually take ownership before installation: https://github.com/krlvm/BeautySearch/issues/11#issuecomment-860113080

**Comment by SOI7** [comment]
Any news on this?

**Comment by krlvm** [comment]
It appears that the WebView which is embedded in Search is configured to disallow loading web pages from local network even when `checknetisolation` is configured, while it is needed to run a local web server which will add CORS header to Google's responses, because it will not load otherwise.
I have an idea of implementing a proxy server instead of the web server and proxy only Search App requests through it with NDIS, but it is a more complex solution.

**Comment by SOI7** [comment]
> It appears that the WebView which is embedded in Search is configured to disallow loading web pages from local network even when `checknetisolation` is configured, while it is needed to run a local web server which will add CORS header to Google's responses, because it will not load otherwise. I have an idea of implementing a proxy server instead of the web server and proxy only Search App requests through it with NDIS, but it is a more complex solution.

Does this affect only Google, or web engines in general? I wouldn't mind having at least Bing tbh

**Comment by krlvm** [comment]
> > It appears that the WebView which is embedded in Search is configured to disallow loading web pages from local network even when `checknetisolation` is configured, while it is needed to run a local web server which will add CORS header to Google's responses, because it will not load otherwise. I have an idea of implementing a proxy server instead of the web server and proxy only Search App requests through it with NDIS, but it is a more complex solution.
> 
> Does this affect only Google, or web engines in general? I wouldn't mind having at least Bing tbh

IIRC Bing loads correctly

**Comment by NicholasBottone** [comment]
> IIRC Bing loads correctly

Would you consider enabling Bing search in the main release if that portion is ready while you are working on other custom search engines? The beta release is a bit outdated at this point.

**Comment by krlvm** [comment]
> > IIRC Bing loads correctly
> 
> Would you consider enabling Bing search in the main release if that portion is ready while you are working on other custom search engines? The beta release is a bit outdated at this point.

Unfortunately, looks like this is no longer possible starting with build 1904X.1618+

**Comment by SOI7** [comment]
> > > IIRC Bing loads correctly
> > 
> > 
> > Would you consider enabling Bing search in the main release if that portion is ready while you are working on other custom search engines? The beta release is a bit outdated at this point.
> 
> Unfortunately, looks like this is no longer possible starting with build 1904X.1618+

I guess because of the new Search Highlights feature

**Comment by krlvm** [comment]
> > > > IIRC Bing loads correctly
> > > 
> > > 
> > > Would you consider enabling Bing search in the main release if that portion is ready while you are working on other custom search engines? The beta release is a bit outdated at this point.
> > 
> > 
> > Unfortunately, looks like this is no longer possible starting with build 1904X.1618+
> 
> I guess because of the new Search Highlights feature

Actually, the native Bing search could be re-enabled in older versions by editing the code of the bundle's JavaScript files, but this no longer works - for some reason, network requests don't pass.
Maybe this can be solved after more thorough inspection of the scripts, but they were written in React, which makes it difficult to read without source mappings.

**Comment by krlvm** [comment]
> Neato, I was recommended this repo by github. I have a solution currently that hooks into MS Edge instead of the Start Menu but I'd love to direct traffic your way if you get this working within the Start Menu itself.

This is unlikely to help - the Search Window still uses the deprecated EdgeHTML WebView, including on the latest Insider builds of Windows 11.

The Search Application simply adds an iframe to the document that loads a mini version of Bing search, the main feature of which is the allow CORS header when sending special data in the request.

The address of the WebView itself cannot be changed, and attempts to load the iframe from Google have failed due to CORS. The only thing that can be loaded there is a special version of Google search for iframe embedding, which allows CORS, but it does not fit into this small panel, because without setting cookies or changing the User-Agent, the mobile version cannot be loaded. Other search engines, again, due to CORS, cannot be embedded in an iframe.

A good solution would be to raise a local web server that proxies requests and modifies CORS headers, but it also does not load in the iframe, because firstly, UWP security rules block WebView access to local addresses until you explicitly allow this through PowerShell (this possible to do), and secondly, the WebView itself refuses to load local addresses or addresses on the local network until the appropriate prohibition is disabled in the WebView settings in the XAML or the UI Search App code.

Changing the hosts is also useless, since all these addresses resolve to 127.0.0.1 anyway, but it would be possible to perform a trick using a proxy server that would combine a CORS proxy when requesting a specific address, which is inconvenient, since it will force you to proxy in general, all traffic, or it could be done by writing a driver for the Windows Filtering Platform or using WinDivert, which is too unreasonably tricky for this.

Maybe in a future version I'll just add a web search button to the list of results, but here is also a problem - due to CORS, I can't get the query completion list from search engines, which again loses to the standard Bing Search.

It is also important to note that when search in Bing is enabled, that is, not disabled in the registry, all your even unfinished search queries come to Microsoft on the Bing servers in conjunction with your Microsoft account, even if you are looking for some local file and in general don't want to search the web, regardless of your privacy settings.

**Comment by krlvm** [comment]
> Have you considered registering a URI and having the javascript call that URI for web search? This would allow you to access local addresses as the application registered for that URI will be handling the request, not UWP.

The Search App internal API accessible from JavaScript part provide a way to launch any executable file or URL, so it is possible to launch the default browser without a problems.
```js
bsController.launchUri('https://github.com/');
```

There's also a very simple way of getting the search box input, but there's a problem which is not too simple to solve: we need to to inject the button to the search results which will launch the code above, but it is pretty complicated since the Search UI is written with React.

**Comment by TechLionDev** [comment]
I Have Experience With React And Would Love to contribute to this project!

**Comment by Poopooracoocoo** [comment]
well i do believe the project is open to PRs, despite the lack of a contributing.md file.

**Comment by XPower7125** [comment]
updates?
