### ISSUE TITLE
Change color of acrylic context menu to have a better contrast

### ISSUE THREAD

**Issue by Daksh777** [krlvm/BeautySearch#12]
![image](https://user-images.githubusercontent.com/43648146/127745613-62a39722-d4b6-4481-aeaf-b30a1c01efda.png)
Currently, the background color of the context menu is too bright and is a bit unpleasing to look at, having a darker background color (something like #2B2B2B) would be much more pleasing and have good contrast.

**Comment by krlvm** [comment]
Looks like a bug which I can't reproduce, which Windows 10 verion you're running?

**Comment by Daksh777** [comment]
I'm using 20H2 (19042.1110)

**Comment by krlvm** [comment]
Looks like a bug when Dark theme is forced, change it to Auto:
![image](https://user-images.githubusercontent.com/51774833/127747694-2952da39-bcf2-4566-a35b-043c4e39308e.png)

**Comment by krlvm** [comment]
Should work correctly with Dark theme selected instead of Auto in [version 1.5](https://github.com/krlvm/BeautySearch/releases/tag/v1.5), but it will behave like Auto selected. The difference between Auto and Dark was that when Dark was selected, the dark theme was forced even when Apps Theme in Windows 10 Settings was Light.

**Comment by Daksh777** [comment]
That works well, thank you.
