### ISSUE TITLE
Blank Search Screen

### ISSUE THREAD

**Issue by jruaaa** [krlvm/BeautySearch#17]
When searching, I have to click on the menu in order to show it. https://streamable.com/fq4wp4

**Comment by krlvm** [comment]
Hello.

Unfortunately, this bug is not related to BeautySearch. I got it often even before BeautySearch was developed and continue to encounter it on Windows 10 21H1 on computers not using BeautySearch.

Windows 10 Search App is a window containing the search bar (if not on the taskbar) and an EdgeHTML WebView that provides user interface and fills the rest of the space. BeautySearch is actually a JavaScript file that is loaded into WebView and injects some CSS there.

The gray rectangle you see is not a part of WebView (it is a native Win32 or UWP control), hence it has nothing to do with BeautySearch. As you see, when you resize Start Menu, Search Window gets resized too, so this bug is related either to Start Menu resize, either to graphic drivers problem.

I encounter this rarely and it does not appear for months after reboot or killing `SearchApp.exe` process (it will restart automatically), you can execute this command if you want to fix it without reboot:
`taskkill /f /im SearchApp.exe`

**Comment by jruaaa** [comment]
Hey, this wasn't solved with the mentioned command, https://streamable.com/qwh8pj. I understand that this issue isn't fixed by beautysearch but wanted to put this out there.

**Comment by krlvm** [comment]
I think you need to reboot your PC, you can also restart graphical drivers without rebooting PC using Win+Ctrl+Shift+B, but I don't think it is a graphic drivers issue though

**Comment by jruaaa** [comment]
Do I have to reinstall every time I reboot, rebooting fixed the issue but search went back to stock again.

**Comment by krlvm** [comment]
Please, make sure that `BingSearchEnabled` in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search` is set to 0
