### ISSUE TITLE
Recycle bin doesn't show up

### ISSUE THREAD

**Issue by Poopooracoocoo** [krlvm/BeautySearch#7]
I tried searching for recycle bin but it doesn't show up :/

**Comment by krlvm** [comment]
BeautySearch only changes the appearance of the Search Window, nothing more, so this issue is not related to BeautySearch, if you are able to find Recycle Bin when BeautySearch is not installed, that means that this is a bug that present in the Windows Search that ships with your version of Windows 10 and should be fixed and compatible with BeautySearch in an upcoming Windows 10 release.

**Comment by Poopooracoocoo** [comment]
I'm on Windows 10 2004 to be clear. When Bing searches were on (or before BeautySearch was installed) the recycle bin would show up.

**Comment by krlvm** [comment]
Microsoft updates the internal version of Search every major update, so it will work with 21H1.

**Comment by Poopooracoocoo** [comment]
> so it will work with 21H1.

What do you mean by that? Does searching for the recycle bin on version 2004 not work for you either? Is it fixed in 21H1?

**Comment by krlvm** [comment]
> > so it will work with 21H1.
> 
> What do you mean by that? Does searching for the recycle bin on version 2004 not work for you either? Is it fixed in 21H1?

The issue you talk about is fixed in live version of Bing Search, that runs inside the Windows 10 Search App.
Each version of Windows ships with the latest version of Bing Search on that moment: 19H1 has Bing Search of November 2018, 20H1 has Bing Search of April 2020, the next version of Windows 10 that should be released in 2021 Spring should contain Bing Search at least up to date with November 2020, which I see have fixed your issue.
